### ISSUE TITLE
将 UnityWebRequest 换掉后可能就不支持 webgl

### ISSUE THREAD

**Issue by Bian-Sh** [JasonXuDeveloper/JAsset#1]
将 UnityWebRequest 换掉后可能就不支持 webgl，如果本就不支持，就当我没说，嘿嘿

**Comment by JasonXuDeveloper** [comment]
webgl下不需要热更新啊哈哈，直接更新静态web资源就好，没必要加载ab包说实话

**Comment by JasonXuDeveloper** [comment]
然后的确，httpwebrequest不支持webgl，

> HttpWebRequest is from the System.Net namespace and you can't use any API from the System.Net namespace with WebGL platform.
>
> 来自stackoverflow，https://stackoverflow.com/questions/50307976/httpwebrequest-not-working-with-webgl

**Comment by Bian-Sh** [comment]
> webgl下不需要热更新啊哈哈，直接更新静态web资源就好，没必要加载ab包说实话

对哦，热更主要是说的代码热更，可寻址 理念似乎与webgl 更配

**Comment by JasonXuDeveloper** [comment]
> > webgl下不需要热更新啊哈哈，直接更新静态web资源就好，没必要加载ab包说实话
> 
> 对哦，热更主要是说的代码热更，可寻址 理念似乎与webgl 更配

其实热更主要是不需要用户去应用市场去更新游戏，而是直接在游戏内对其资源和代码热更，但是webgl是可以随时更新的，因为用户只要刷新页面（在没有缓存的情况下）就能玩到最新的游戏，所以webgl平台其实没必要热更新

**Comment by Bian-Sh** [comment]
get 到了
